diary('lanczos_performance.log');
fprintf(1, '-------------------------------------------\n');
fprintf(1, '            CPU Single Core                \n');
fprintf(1, '-------------------------------------------\n');
fprintf(1, 'Processing KPIS001.jpg...\n');
bootstrap_c('KPIS001', 10, 50, 12);
fprintf(1,    '\nProcessing nCPM4.jpg ...\n');
bootstrap_c('nCPM4', 10, 50, 48);
fprintf(1, '\nProcessing capillary_skeletal_muscle.jpg...\n');
bootstrap_c('capillary_skeletal_muscle', 10, 50, 50);
fprintf(1, '\nProcessing capillary_retina.jpg...\n');
bootstrap_c('capillary_retina', 10, 50, 199);
fprintf(1,    '\nProcessing nCPM9.jpg ...\n');
bootstrap_c('nCPM9', 10, 50, 250);
fprintf(1,    '\nProcessing nCPM9_large.jpg ...\n');
bootstrap_c('nCPM9_large', 10, 50, 250);
fprintf(1, '-------------------------------------------\n');
fprintf(1, '            CPU Multithreaded              \n');
fprintf(1, '-------------------------------------------\n');
fprintf(1, '----------- # threads = 4 -----------------\n');
setenv('OMP_NUM_THREADS', '4');
fprintf(1, 'Processing KPIS001.jpg...\n');
bootstrap_omp('KPIS001', 10, 50, 12);
fprintf(1,    '\nProcessing nCPM4.jpg ...\n');
bootstrap_omp('nCPM4', 10, 50, 48);
fprintf(1, '\nProcessing capillary_skeletal_muscle.jpg...\n');
bootstrap_omp('capillary_skeletal_muscle', 10, 50, 50);
fprintf(1, '\nProcessing capillary_retina.jpg...\n');
bootstrap_omp('capillary_retina', 10, 50, 199);
fprintf(1,    '\nProcessing nCPM9.jpg ...\n');
bootstrap_omp('nCPM9', 10, 50, 250);
fprintf(1,    '\nProcessing nCPM9_large.jpg ...\n');
bootstrap_omp('nCPM9_large', 10, 50, 250);
fprintf(1, '----------- # threads = 8 -----------------\n');
setenv('OMP_NUM_THREADS', '8');
fprintf(1, 'Processing KPIS001.jpg...\n');
bootstrap_omp('KPIS001', 10, 50, 12);
fprintf(1,    '\nProcessing nCPM4.jpg ...\n');
bootstrap_omp('nCPM4', 10, 50, 48);
fprintf(1, '\nProcessing capillary_skeletal_muscle.jpg...\n');
bootstrap_omp('capillary_skeletal_muscle', 10, 50, 50);
fprintf(1, '\nProcessing capillary_retina.jpg...\n');
bootstrap_omp('capillary_retina', 10, 50, 199);
fprintf(1,    '\nProcessing nCPM9.jpg ...\n');
bootstrap_omp('nCPM9', 10, 50, 250);
fprintf(1,    '\nProcessing nCPM9_large.jpg ...\n');
bootstrap_omp('nCPM9_large', 10, 50, 250);
fprintf(1, '----------- # threads = 16 -----------------\n');
setenv('OMP_NUM_THREADS', '16');
fprintf(1, 'Processing KPIS001.jpg...\n');
bootstrap_omp('KPIS001', 10, 50, 12);
fprintf(1,    '\nProcessing nCPM4.jpg ...\n');
bootstrap_omp('nCPM4', 10, 50, 48);
fprintf(1, '\nProcessing capillary_skeletal_muscle.jpg...\n');
bootstrap_omp('capillary_skeletal_muscle', 10, 50, 50);
fprintf(1, '\nProcessing capillary_retina.jpg...\n');
bootstrap_omp('capillary_retina', 10, 50, 199);
fprintf(1,    '\nProcessing nCPM9.jpg ...\n');
bootstrap_omp('nCPM9', 10, 50, 250);
fprintf(1,    '\nProcessing nCPM9_large.jpg ...\n');
bootstrap_omp('nCPM9_large', 10, 50, 250);
fprintf(1, '----------- # threads = 24 -----------------\n');
setenv('OMP_NUM_THREADS', '24');
fprintf(1, 'Processing KPIS001.jpg...\n');
bootstrap_omp('KPIS001', 10, 50, 12);
fprintf(1,    '\nProcessing nCPM4.jpg ...\n');
bootstrap_omp('nCPM4', 10, 50, 48);
fprintf(1, '\nProcessing capillary_skeletal_muscle.jpg...\n');
bootstrap_omp('capillary_skeletal_muscle', 10, 50, 50);
fprintf(1, '\nProcessing capillary_retina.jpg...\n');
bootstrap_omp('capillary_retina', 10, 50, 199);
fprintf(1,    '\nProcessing nCPM9.jpg ...\n');
bootstrap_omp('nCPM9', 10, 50, 250);
fprintf(1,    '\nProcessing nCPM9_large.jpg ...\n');
bootstrap_omp('nCPM9_large', 10, 50, 250);

fprintf(1, '-------------------------------------------\n');
fprintf(1, '            GPU with Lanczos               \n');
fprintf(1, '-------------------------------------------\n');
setenv('OMP_NUM_THREADS', '1');
fprintf(1, 'Processing KPIS001.jpg...\n');
bootstrap_gpu('KPIS001', 10, 50, 12);
fprintf(1,    '\nProcessing nCPM4.jpg ...\n');
bootstrap_gpu('nCPM4', 10, 50, 48);
fprintf(1, '\nProcessing capillary_skeletal_muscle.jpg...\n');
bootstrap_gpu('capillary_skeletal_muscle', 10, 50, 50);
fprintf(1, '\nProcessing capillary_retina.jpg...\n');
bootstrap_gpu('capillary_retina', 10, 50, 199);
fprintf(1,    '\nProcessing nCPM9.jpg ...\n');
bootstrap_gpu('nCPM9', 10, 50, 250);
fprintf(1,    '\nProcessing nCPM9_large.jpg ...\n');
bootstrap_gpu('nCPM9_large', 10, 50, 250);

fprintf(1, '-------------------------------------------\n');
fprintf(1, '            GPU with general solver        \n');
fprintf(1, '-------------------------------------------\n');
fprintf(1, 'Processing KPIS001.jpg...\n');
bootstrap_gpu_full('KPIS001', 10, 50);
fprintf(1,    '\nProcessing nCPM4.jpg ...\n');
bootstrap_gpu_full('nCPM4', 10, 50);
fprintf(1, '\nProcessing capillary_skeletal_muscle.jpg...\n');
bootstrap_gpu_full('capillary_skeletal_muscle', 10, 50);
fprintf(1, '\nProcessing capillary_retina.jpg...\n');
bootstrap_gpu_full('capillary_retina', 10, 50);
fprintf(1,    '\nProcessing nCPM9.jpg ...\n');
bootstrap_gpu_full('nCPM9', 10, 50);

diary off;
